### ISSUE TITLE
Bed annotation

### ISSUE THREAD

**Issue by TheSergeyPixel** [SimCab-CHU/ifCNV#4]
Hi!

I was trying ifCNV for some of my datasets and was wondering if having bed file without any annotations (chr, start, end columns only) is any different to having the bed annotated with exon number and gene names?

**Comment by SimCab-CHU** [comment]
Hi,

As it is of great importance for ifCNV you need to comply to some key points:
- the BED file must have (at least) 4 columns, the three first are the coordinates of the baited genomic regions and the forth one is a string describing these regions.
- The forth column is the name of the targeted region and it must be set carefuly as it will be used to compute the localization score (see the Resolution paragraph in the README file)

Thanks for using **ifCNV**!

SCA

**Comment by TheSergeyPixel** [comment]
Got it, thank you for your response!
